controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
add_gallery:
  path: /api/gallery/add
  controller: App\Controller\GalleryController::addGallery
  methods: [POST]

api_gallery_list:
  path: /api/gallery
  controller: App\Controller\GalleryController::getGalleryList
  methods: GET

api_add_news:
    path: /api/add-news
    methods: [POST]
    controller: App\Controller\NewsController::addNews

api_get_news:
    path: /api/news
    controller: App\Controller\NewsController::getNews
    methods: [GET]

add_photo:
    path: /api/photos/{galleryId}
    controller: App\Controller\GalleryController::addPhoto
    methods: POST

api_get_photos:
    path: /api/get_photos
    controller: App\Controller\PhotoController::getPhotos
    methods: [GET]

gallery_photos_get:
  path: /api/gallery/{id}/photos
  controller: App\Controller\GalleryController::getGalleryPhotos
  methods: GET

gallery_photos:
    path: /gallery/{id}
    controller: App\Controller\GalleryController::getGalleryPhotos